CREATE DATABASE AULA_BD;
USE AULA_BD;

CREATE TABLE PROFESSORES (
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(50) NOT NULL,
	Apelido VARCHAR(15) NOT NULL
);

CREATE TABLE SALAS (
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(30) NOT NULL,
	NumeroComputadores INT NOT NULL,
	NumeroCadeiras INT NOT NULL,
	IsLab BIT NOT NULL,
	Disponivel BIT NOT NULL
);
CREATE TABLE DISCIPLINAS (
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(60) NOT NULL,
	Sigla VARCHAR(8) NOT NULL
);

CREATE TABLE CURSOS (
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(50) NOT NULL,
	Turno VARCHAR(10) NOT NULL,
	Sigla VARCHAR(10) NOT NULL
);

CREATE TABLE CURSO_DISCIPLINA (
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Modulo VARCHAR(15) NOT NULL,
	Disciplina_Id INT NOT NULL,
	Curso_Id INT NOT NULL,
	CONSTRAINT  FK_DISCIPLINA   FOREIGN KEY (Disciplina_Id) REFERENCES DISCIPLINAS(Id),
	CONSTRAINT  FK_CURSOS       FOREIGN KEY (Curso_Id)      REFERENCES CURSOS(Id)
);

--Acrescentando um campo para professor
ALTER TABLE CURSO_DISCIPLINA
ADD Professor_Id INT NOT NULL

--Agora é necessário atualizar todos os registros com algum valor no campo Professor_Id
update CURSO_DISCIPLINA set Professor_Id = 1

--Criando uma Constraint com a tabela de professores
ALTER TABLE CURSO_DISCIPLINA
ADD CONSTRAINT FK_PROFESSORES FOREIGN KEY (Professor_Id) REFERENCES PROFESSORES(Id)
	

